AllCops:
  NewCops: enable
  Exclude:
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"

  DisplayCopNames: true

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/AbcSize:
  Max: 70
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  IgnoredMethods: ['describe']
  Max: 30


Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
